"""
Linux crash dump parser using GDB.
Optimized for Python 3.12.10 with modern async patterns.
"""

import re
import asyncio
from pathlib import Path
from typing import Any

from .types import CrashData, DumpType, FilePath, ParserError, DebuggerNotFoundError, DebuggerTimeoutError, StackFrame, ModuleInfo
from app.core.config import settings
from app.core.logging import get_logger

logger = get_logger(__name__)


class LinuxCrashParser:
    """
    Parse Linux core dumps using GDB.
    Uses Python 3.12 optimizations for better performance.
    """
    
    def __init__(self):
        self.gdb_path = getattr(settings, 'GDB_PATH', '/usr/bin/gdb')
        self.timeout = getattr(settings, 'DEBUGGER_TIMEOUT_SECONDS', 120)
    
    async def parse(self, core_path: FilePath, executable_path: FilePath | None = None) -> CrashData:
        """
        Parse Linux core dump using GDB.
        
        Args:
            core_path: Path to core dump file
            executable_path: Optional path to executable binary
            
        Returns:
            CrashData object with parsed information
            
        Raises:
            DebuggerNotFoundError: If GDB is not installed
            DebuggerTimeoutError: If GDB times out
            ParserError: If parsing fails
        """
        logger.info(f"Parsing Linux core dump: {core_path}")
        
        # Verify GDB exists
        if not Path(self.gdb_path).exists():
            raise DebuggerNotFoundError(
                f"GDB not found at: {self.gdb_path}. "
                "Install with: sudo apt-get install gdb"
            )
        
        # Build GDB command
        gdb_commands = [
            'set pagination off',
            'set width 0',
            'set height 0',
            'info program',
            'thread apply all bt full',
            'info threads',
            'info registers',
            'info sharedlibrary',
            'quit',
        ]
        
        cmd = [self.gdb_path, '--batch']
        
        if executable_path:
            cmd.extend(['--exec', executable_path])
        
        cmd.extend(['--core', core_path])
        
        for gdb_cmd in gdb_commands:
            cmd.extend(['--eval-command', gdb_cmd])
        
        # Execute GDB
        try:
            process = await asyncio.create_subprocess_exec(
                *cmd,
                stdout=asyncio.subprocess.PIPE,
                stderr=asyncio.subprocess.PIPE
            )
            
            stdout, _ = await asyncio.wait_for(
                process.communicate(),
                timeout=self.timeout
            )
            
            output = stdout.decode('utf-8', errors='replace')
            
            if not output:
                raise ParserError("GDB produced no output")
            
            return self._parse_gdb_output(output, core_path)
            
        except asyncio.TimeoutError:
            logger.error(f"GDB timeout after {self.timeout}s")
            raise DebuggerTimeoutError(f"GDB timeout after {self.timeout} seconds")
        except Exception as e:
            logger.error(f"GDB execution failed: {e}", exc_info=True)
            raise ParserError(f"GDB execution failed: {str(e)}")
    
    def _parse_gdb_output(self, output: str, core_path: FilePath) -> CrashData:
        """
        Extract structured data from GDB output.
        Uses Python 3.12 f-string improvements for better error messages.
        """
        crash_data = CrashData(
            platform="Linux",
            dump_type=DumpType.LINUX_CORE
        )
        
        # Extract signal information (e.g., SIGSEGV, SIGABRT)
        signal_match = re.search(
            r'Program terminated with signal (\w+),\s*(.+?)(?:\.|$)',
            output,
            re.IGNORECASE
        )
        if signal_match:
            crash_data.signal = signal_match.group(1)
            crash_data.exception_message = signal_match.group(2).strip()
            crash_data.exception_code = self._signal_to_code(signal_match.group(1))
            logger.info(f"Signal: {crash_data.signal} - {crash_data.exception_message}")
        
        # Extract core file info
        core_match = re.search(r'Core was generated by `([^`]+)`', output)
        if core_match:
            logger.info(f"Core generated by: {core_match.group(1)}")
        
        # Extract stack trace
        crash_data.stack_trace = self._extract_stack_trace(output)
        
        # Extract thread information
        crash_data.threads = self._extract_threads(output)
        crash_data.thread_count = len(crash_data.threads)
        
        # Extract loaded libraries
        crash_data.loaded_modules = self._extract_shared_libraries(output)
        
        # Extract registers
        registers_section = re.search(
            r'(rax\s+0x[0-9a-f]+.*?)(?:\n\n|\Z)',
            output,
            re.IGNORECASE | re.DOTALL
        )
        if registers_section:
            crash_data.registers = registers_section.group(1).strip()
        
        # Extract architecture
        if 'rip' in output.lower() or 'rax' in output.lower():
            crash_data.architecture = 'x64'
        elif 'eip' in output.lower() or 'eax' in output.lower():
            crash_data.architecture = 'x86'
        elif 'pc' in output.lower() and 'arm' in output.lower():
            crash_data.architecture = 'ARM'
        
        return crash_data
    
    def _signal_to_code(self, signal_name: str) -> str:
        """
        Convert Linux signal to exception code.
        Using Python 3.12 match-case for cleaner code.
        """
        match signal_name.upper():
            case 'SIGSEGV':
                return '0x0000000B'  # Segmentation fault
            case 'SIGABRT':
                return '0x00000006'  # Abort
            case 'SIGFPE':
                return '0x00000008'  # Floating point exception
            case 'SIGILL':
                return '0x00000004'  # Illegal instruction
            case 'SIGBUS':
                return '0x00000007'  # Bus error
            case 'SIGTRAP':
                return '0x00000005'  # Trace/breakpoint trap
            case 'SIGKILL':
                return '0x00000009'  # Killed
            case 'SIGTERM':
                return '0x0000000F'  # Terminated
            case _:
                return '0x00000000'  # Unknown
    
    def _extract_stack_trace(self, output: str) -> list[StackFrame]:
        """Extract stack trace from GDB output"""
        frames: list[StackFrame] = []
        
        # Pattern: #0  0x00007ffff7a42cf0 in function_name () from /lib/x86_64-linux-gnu/libc.so.6
        pattern = r'#(\d+)\s+(0x[0-9a-f]+)\s+in\s+([^\s]+)\s+\(.*?\)\s+(?:from|at)\s+(.+)'
        
        for line in output.split('\n'):
            match = re.match(pattern, line, re.IGNORECASE)
            if match:
                frame_num = int(match.group(1))
                address = match.group(2)
                function = match.group(3)
                location = match.group(4).strip()
                
                # Extract module name from path
                module = Path(location).name if '/' in location else location
                
                frames.append(StackFrame(
                    frame_number=frame_num,
                    function=function,
                    module=module,
                    offset=address,
                    source_line=location
                ))
                
                if len(frames) >= getattr(settings, 'MAX_STACK_DEPTH', 50):
                    break
        
        return frames
    
    def _extract_threads(self, output: str) -> list[dict[str, Any]]:
        """Extract thread information from GDB output"""
        threads = []
        
        # Pattern: * 1    Thread 0x7ffff7fc7740 (LWP 12345) "program_name"
        pattern = r'[*\s]\s*(\d+)\s+Thread\s+(0x[0-9a-f]+)\s+\(LWP\s+(\d+)\)\s*"?([^"]*)"?'
        
        for line in output.split('\n'):
            match = re.match(pattern, line)
            if match:
                threads.append({
                    "thread_id": int(match.group(1)),
                    "address": match.group(2),
                    "lwp": int(match.group(3)),
                    "name": match.group(4).strip() if match.group(4) else None,
                    "is_current": line.strip().startswith('*')
                })
        
        return threads
    
    def _extract_shared_libraries(self, output: str) -> list[ModuleInfo]:
        """Extract loaded shared libraries"""
        libraries: list[ModuleInfo] = []
        
        # Pattern: 0x00007ffff7fc7000  0x00007ffff7fe8000  /lib64/ld-linux-x86-64.so.2
        pattern = r'(0x[0-9a-f]+)\s+(0x[0-9a-f]+)\s+(.+\.so[^\s]*)'
        
        for line in output.split('\n'):
            match = re.match(pattern, line, re.IGNORECASE)
            if match:
                lib_path = match.group(3).strip()
                base_addr = match.group(1)
                end_addr = match.group(2)
                # Calculate size from addresses
                size = hex(int(end_addr, 16) - int(base_addr, 16))
                
                libraries.append(ModuleInfo(
                    name=Path(lib_path).name,
                    path=lib_path,
                    base_address=base_addr,
                    size=size
                ))
                
                if len(libraries) >= 100:  # Limit to first 100
                    break
        
        return libraries
